global:
  resolve_timeout: 1m # Faster resolution notifications
  slack_api_url: "https://hooks.slack.com/services/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"

route:
  group_by: ["alertname", "job"]
  group_wait: 10s
  group_interval: 45s
  repeat_interval: 4h
  receiver: "slack-notifications"

receivers:
  - name: "slack-notifications"
    slack_configs:
      - channel: "#alerts"
        send_resolved: true
        title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
        color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
