groups:
  - name: probe-alerts
    rules:
      - alert: ProbeFailureThresholdExceeded
        expr: probe_success == 0
        for: 45s
        labels:
          severity: critical
        annotations:
          summary: "Probe failure detected"
          description: "Probe {{ $labels.instance }} has been failing for 45 seconds, which may trigger Kubernetes restarts."

      - alert: HighProbeFailureRate
        expr: sum(rate(probe_success{job="blackbox"}[5m]) == 0) / sum(rate(probe_success{job="blackbox"}[5m])) > 0.1
        for: 45s
        labels:
          severity: warning
        annotations:
          summary: "High probe failure rate detected"
          description: "More than 10% of probes are failing in the last 10 minutes."

      - alert: SlowResponseTime
        expr: probe_duration_seconds > 1
        for: 45s
        labels:
          severity: warning
        annotations:
          summary: "Slow probe response time"
          description: "Probe {{ $labels.instance }} response time is above 1 second for more than 5 minutes."
