# Flask-app
# Service
apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  selector:
    app: flask-app-rc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5050
  type: LoadBalancer
---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
  namespace: eks-todo-list-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flask-app-rc
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: flask-app-rc
    spec:
      containers:
        - name: flask-app
          image: yuwei2002/flask-todo-app:v3 # latest
          ports:
            - containerPort: 5050
          env:
            - name: MONGO_HOST
              value: "mongodb"
            - name: MONGO_PORT
              value: "27017"
          resources:
            requests:
              cpu: "0.3"
              memory: "256Mi"
            limits:
              cpu: "0.5"
              memory: "512Mi"
          imagePullPolicy: Always
          livenessProbe: # Http Liveness Probe
            httpGet:
              path: /health
              port: 5050
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe: # Http Readiness Probe
            httpGet:
              path: /ready
              port: 5050
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
