services:
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=camp2016
    volumes:
      - mongo_data:/data/db

  flask_app:
    image: "flask-app:latest"  # Use pre-built image
    ports:
      - "5050:5050"
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
volumes:
  mongo_data:
